## No 1

In [1]:
import numpy as np

# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[13, 21, 34], [46, 59, 67]])
print(X)

[[13 21 34]
 [46 59 67]]


In [2]:
# tampilkan ukuran dari matrix X
print(f"Ukuran matrix X: {X.shape}")

Ukuran matrix X: (2, 3)


In [3]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 0])

[13 46]


In [4]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
print(X[:, 1])

[21 59]


## No 2

### Pytorch

In [5]:
import torch as pt

# ulangi soal nomor 1 menggunakan pytorch

# buat matrix X berukuran 2x3
X = pt.tensor([[13, 21, 34], [46, 59, 67]])
print(X)

# tampilkan ukuran dari matrix X
print(f"Ukuran matrix X: {X.shape}")

# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 0].tolist())

# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 1].tolist())

tensor([[13, 21, 34],
        [46, 59, 67]])
Ukuran matrix X: torch.Size([2, 3])
[13, 46]
[21, 59]


### Tensorflow

In [6]:
import tensorflow as tf

# buat matrix X berukuran 2x3
X = tf.Variable([[13, 21, 34], [46, 59, 67]])
print(X)

# tampilkan ukuran dari matrix X
print(f"Ukuran matrix X: {X.shape}")

# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 0].numpy())

# tampilkan seluruh elemen dari kolom kedua dari matrix X
print(X[:, 1].numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[13, 21, 34],
       [46, 59, 67]])>
Ukuran matrix X: (2, 3)
[13 46]
[21 59]
