## No 1

In [1]:
import numpy as np

# buat vector x_np dengan ukuran 3x1
x_np = np.array([[13], [17], [30]])
print(x_np)

[[13]
 [17]
 [30]]


In [2]:
# buat vektor y_np dengan ukuran 3x1
y_np = np.array([[18], [22], [40]])
print(y_np)

[[18]
 [22]
 [40]]


In [3]:
# hitung panjang vector x_np
len(x_np)

3

In [4]:
# tampilkan ukuran vector x_np
x_np.shape

(3, 1)

In [5]:
# tampilkan tipe data dari vector x_np
x_np.dtype

dtype('int32')

In [6]:
# akses elemen pertama dari vector x_np
x_np[0]

array([13])

In [7]:
# tampilkan tipe data elemen pertama dari vector x_np
x_np[0].dtype

dtype('int32')

## No 2

In [8]:
# lakukan transpose pada vector x_np dan simpan pada variabel x_t
x_t = x_np.T
print(x_t)

[[13 17 30]]


In [9]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [10]:
# lakukan transpose pada vector y_np dan simpan pada variabel y_t
y_t = y_np.T
print(y_t)

[[18 22 40]]


## No 3

### Pytorch

In [11]:
import torch as pt

# buat vector x_pt dengan ukuran 3x1 menggunakan pytorch dan ukuran dari vector x_pt
x_pt = pt.tensor([13, 17, 30])
print(x_pt)
x_pt.shape

tensor([13, 17, 30])


torch.Size([3])

In [12]:
# buat vector y_pt dengan ukuran 3x1 menggunakan pytorch dan ukuran dari vector y_pt
y_pt = pt.tensor([18, 22, 40])
print(y_pt)
y_pt.shape

tensor([18, 22, 40])


torch.Size([3])

In [13]:
# lakukan transpose pada vector x_pt dan simpan pada variabel x_pT
x_pT = x_pt.T
print(x_pT)
x_pT.shape

tensor([13, 17, 30])


C:\Users\lwnovo\AppData\Local\Temp\ipykernel_20116\2924804590.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4483.)
  x_pT = x_pt.T


torch.Size([3])

### Tensorflow

In [14]:
import tensorflow as tf

# buat vector x_pt dengan ukuran 3x1 menggunakan tensorflow dan ukuran dari vector x_pt
x_tf = tf.Variable([13, 17, 30], dtype = tf.int32)
print(x_tf)
x_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([13, 17, 30])>


TensorShape([3])

In [15]:
# buat vector y_pt dengan ukuran 3x1 menggunakan tensorflow dan ukuran dari vector y_pt
y_tf = tf.Variable([18, 22, 40], dtype = tf.int32)
print(y_tf)
y_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([18, 22, 40])>


TensorShape([3])

In [16]:
# lakukan transpose pada vector x_tf dan simpan pada variabel x_tF
x_tF = tf.transpose(x_tf)
print(x_tF)
x_tF.shape

tf.Tensor([13 17 30], shape=(3,), dtype=int32)


TensorShape([3])