# No 1

In [2]:
import numpy as np

# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[12, 24, 36], [16, 32, 48]])
print(X)

[[12 24 36]
 [16 32 48]]


In [1]:
import torch as pt

# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = pt.tensor([[13, 26, 39], [15, 30, 45]])
print(X_pt)

tensor([[13, 26, 39],
        [15, 30, 45]])


In [3]:
import tensorflow as tf

# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[14, 28, 42], [18, 36, 54]])
print(X_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[14, 28, 42],
       [18, 36, 54]])>


In [5]:
# lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar
X*2, X_pt*2, X_tf*2

(array([[24, 48, 72],
        [32, 64, 96]]),
 tensor([[26, 52, 78],
         [30, 60, 90]]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 28,  56,  84],
        [ 36,  72, 108]])>)

In [6]:
# lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
X+8, X_pt+8, X_tf+8

(array([[20, 32, 44],
        [24, 40, 56]]),
 tensor([[21, 34, 47],
         [23, 38, 53]]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[22, 36, 50],
        [26, 44, 62]])>)

In [7]:
# lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
X-3, X_pt-3, X_tf-3

(array([[ 9, 21, 33],
        [13, 29, 45]]),
 tensor([[10, 23, 36],
         [12, 27, 42]]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11, 25, 39],
        [15, 33, 51]])>)

# No 2

In [8]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array([[23, 32, 45], [42, 54, 67]])
print(Y)

[[23 32 45]
 [42 54 67]]


In [9]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = pt.tensor([[24, 33, 46], [43, 55, 68]])
print(Y_pt)

tensor([[24, 33, 46],
        [43, 55, 68]])


In [10]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[25, 34, 47], [44, 56, 69]])
print(Y_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 34, 47],
       [44, 56, 69]])>


In [11]:
# kalikan matrix X dengan Y
X*Y

array([[ 276,  768, 1620],
       [ 672, 1728, 3216]])

In [12]:
# kalikan matrix X_pt dengan Y_pt
X_pt*Y_pt

tensor([[ 312,  858, 1794],
        [ 645, 1650, 3060]])

In [13]:
# kalikan matrix X_tf dengan Y_tf
X_tf*Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 350,  952, 1974],
       [ 792, 2016, 3726]])>