# No 1

In [1]:
import numpy as np
import torch as pt
import tensorflow as tf

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([
    [7, 54, 36],
    [86, 32, 8]
])
print(X)

[[ 7 54 36]
 [86 32  8]]


In [ ]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()

223

In [2]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.constant([[67, 54, 34], [67, 3, 28]])
print(X_tf)

tf.Tensor(
[[67 54 34]
 [67  3 28]], shape=(2, 3), dtype=int32)


In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = pt.tensor([
    [47, 4, 39],
    [37, 23, 68]
])
print(X_pt)

tensor([[47,  4, 39],
        [37, 23, 68]])


# No 2

In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X
X.sum()

223

In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
x_pt = pt.sum(X_pt)
print(x_pt)

tensor(218)


In [3]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
X_tf = tf.reduce_sum(X_tf)
print(X_tf)

tf.Tensor(253, shape=(), dtype=int32)


# No 3

In [ ]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
X_row = np.sum(X, axis=1)
print(X_row)

[ 97 126]


In [ ]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
X_pt_row = pt.sum(X_pt, axis=1)
print(X_pt_row)

tensor([ 90, 128])


In [ ]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
X_tf_row = tf.reduce_sum(X_tf, axis=1)
print(X_tf_row.numpy())

[155  98]


# No 4

In [ ]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
X_col = np.sum(X, axis=0)
print(X_col)

[93 86 44]


In [ ]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
X_pt_col = pt.sum(X_pt, axis=0)
print(X_pt_col)

tensor([ 84,  27, 107])


In [ ]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
X_tf_col = tf.reduce_sum(X_tf, axis=0)
print(X_tf_col.numpy())

[134  57  62]


# No 5

In [ ]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf
X_min = np.min(X)
X_pt_min = pt.min(X_pt)
X_tf_min = tf.reduce_min(X_tf)
print(f"Nilai minimal dari X Adalah : {X_min}")
print(f"Nilai minimal dari X_pt Adalah : {X_pt_min}")
print(f"Nilai minimal dari X_tf Adalah : {X_tf_min.numpy()}")

Nilai minimal dari X Adalah : 7
Nilai minimal dari X_pt Adalah : 4
Nilai minimal dari X_tf Adalah : 3


In [ ]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf
X_max = np.max(X)
X_pt_max = pt.max(X_pt)
X_tf_max = tf.reduce_max(X_tf)
print(f"Nilai maksimal dari X Adalah : {X_max}")
print(f"Nilai maksimal dari X_pt Adalah : {X_pt_max}")
print(f"Nilai maksimal dari X_tf Adalah : {X_tf_max.numpy()}")

Nilai maksimal dari X Adalah : 86
Nilai maksimal dari X_pt Adalah : 68
Nilai maksimal dari X_tf Adalah : 67


In [ ]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
X_pt = X_pt.float()

X_mean = np.mean(X)
X_pt_mean = pt.mean(X_pt)
X_tf_mean = tf.reduce_mean(X_tf)
print(f"Nilai Rata-Rata dari X Adalah : {X_mean}")
print(f"Nilai Rata-Rata dari X_pt Adalah : {X_pt_mean}")
print(f"Nilai Rata-Rata dari X_tf Adalah : {X_tf_mean.numpy()}")

Nilai Rata-Rata dari X Adalah : 37.166666666666664
Nilai Rata-Rata dari X_pt Adalah : 36.33333206176758
Nilai Rata-Rata dari X_tf Adalah : 42


# No 6

In [ ]:
# hitung hasil perkalian seluruh elemen matrix X
X_prod

299593728

In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_pt
X_pt_prod = pt.prod(X_pt)
print(X_pt_prod)

tensor(4.2429e+08)


In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_tf
X_tf_prod = tf.reduce_prod(X_tf)
print(X_tf_prod.numpy())

692311536
