# No 1

In [11]:
import numpy as np

# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[12, 24, 36], [16, 32, 48]])
print(X)

[[12 24 36]
 [16 32 48]]


In [12]:
import torch as pt

# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = pt.tensor([[13, 26, 39], [15, 30, 45]])
print(X_pt)

tensor([[13, 26, 39],
        [15, 30, 45]])


In [13]:
import tensorflow as tf

# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[14, 28, 42], [18, 36, 54]])
print(X_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[14, 28, 42],
       [18, 36, 54]])>


# No 2

In [14]:
# lakukan transpose pada matrix X, X_pt dan X_tf
X_t = X.T
X_pt_t = X_pt.T
X_tf_t = tf.transpose(X_tf)
print(X_t)
print()
print(X_pt_t)
print()
print(X_tf_t)

[[12 16]
 [24 32]
 [36 48]]

tensor([[13, 15],
        [26, 30],
        [39, 45]])

tf.Tensor(
[[14 18]
 [28 36]
 [42 54]], shape=(3, 2), dtype=int32)
