# No 1

In [6]:
import numpy as np

# buat vector x dan y dengan ukuran 1x3 menggunakan numpy
x = np.array([14, 28, 63])
y = np.array([43, 95, 67])
print(f"Vector x : {x}")
print(f"Vector y : {y}")

Vector x : [14 28 63]
Vector y : [43 95 67]


In [7]:
import torch as pt

# buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
x_pt = pt.tensor([44, 68, 23])
y_pt = pt.tensor([48, 65, 57])
print(f"Vector x_pt : {x_pt}")
print(f"Vector y_pt : {y_pt}")

Vector x_pt : tensor([44, 68, 23])
Vector y_pt : tensor([48, 65, 57])


In [8]:
import tensorflow as tf

# buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
x_tf = tf.Variable([46, 48, 63])
y_tf = tf.Variable([68, 35, 52])
print(f"Vector x_tf : {x_tf}")
print(f"Vector y_tf : {y_tf}")

Vector x_tf : <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([46, 48, 63])>
Vector y_tf : <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([68, 35, 52])>


# No 2

In [10]:
# hitung perkalian dot product antara vector x dan vector y
np.dot(x, y)

7483

In [11]:
# hitung perkalian dot product antara vector x_pt dan vector y_pt
pt.dot(x_pt, y_pt)

tensor(7843)

In [13]:
# hitung perkalian dot product antara vector x_tf dan vector y_tf
tf.tensordot(x_tf, y_tf, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=8084>

# No 3

In [ ]:
import PIL.Image as Image

# lakukan perhitungan excercise menggunakan collab

img = Image.open('C:/Users/lwnovo/Documents/VSCode/Github/2. Common Tensors Operations/image.png')
img.show()


In [ ]:
# Nomor 1 - Apa Transpose dari matrix Y?
Y = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])
print(f"Matrix Y : \n{Y}")
Y_t = Y.T
print(f"Matrix Y Transpose : \n{Y_t}")

Matrix Y : 
[[ 42   4   7  99]
 [-99  -3  17  22]]
Matrix Y Transpose : 
[[ 42 -99]
 [  4  -3]
 [  7  17]
 [ 99  22]]


In [26]:
# Nomor 2 - Apa Hasil Hadamard Product antara matrix A dan B

A = np.array([[25, 10], [-2, 1]])
B = np.array([[-1, 7], [10, 8]])
print(f"Matrix A : \n{A}")
print(f"Matrix B : \n{B}")

hadamard_product = A * B
print(f"Hadamard Product antara A dan B : \n{hadamard_product}")

Matrix A : 
[[25 10]
 [-2  1]]
Matrix B : 
[[-1  7]
 [10  8]]
Hadamard Product antara A dan B : 
[[-25  70]
 [-20   8]]


In [30]:
# Nomor 3 - Apa hasil dot product dari tensor w dan x
w = np.array([1, 2, 3])
x = np.array([4, 5, 6])
np.dot(w, x)



32