In [5]:
import numpy as np
import torch as pt
import tensorflow as tf


### Numpy

In [12]:
X = np.array([[17, 43, 85], [64, 24, 51], [11, 75, 77]])
print(X)
np.linalg.norm(X)

[[17 43 85]
 [64 24 51]
 [11 75 77]]


168.25872934264063

### Torch

In [18]:
X_pt = pt.tensor([[13, 23, 55], [14, 24, 56], [15, 25, 57]])
X_pt = X_pt.float()
print(X_pt)
pt.norm(X_pt)

tensor([[13., 23., 55.],
        [14., 24., 56.],
        [15., 25., 57.]])


tensor(108.3051)

### Tensorflow

In [19]:
X_tf = tf.Variable([[23, 63, 87], [15, 24, 33], [88, 75, 90]], dtype=tf.float32)
print(X_tf)
tf.norm(X_tf)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[23., 63., 87.],
       [15., 24., 33.],
       [88., 75., 90.]], dtype=float32)>


<tf.Tensor: shape=(), dtype=float32, numpy=188.21795654296875>