In [17]:
import numpy as np
import torch as pt
import tensorflow as tf

# NO 1

In [14]:
# buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[16, 8], [10, 9]])
print(X)

[[16  8]
 [10  9]]


In [15]:
# buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
print(Xinv)

[[ 0.140625 -0.125   ]
 [-0.15625   0.25    ]]


In [18]:
np.dot(Xinv, X)

array([[1., 0.],
       [0., 1.]])

# NO 2

In [ ]:
# selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch
# 4b + 2c = 4
# -5b + -3c = -7

## Numpy

In [24]:
# selesaikan persamaan berikut menggunakan numpy
# 4b + 2c = 4
# -5b + -3c = -7
A = np.array([[4, 2], [-5, -3]])
B = np.array([[4], [-7]])
C = np.linalg.solve(A, B)
print(C)

[[-1.]
 [ 4.]]


## Torch

In [25]:
# selesaikan persamaan berikut menggunakan pytorch
# 4b + 2c = 4
# -5b + -3c = -7
A = pt.tensor([[4, 2], [-5, -3]], dtype=pt.float32)
B = pt.tensor([[4], [-7]], dtype=pt.float32)
C = pt.linalg.solve(A, B)
print(C)

tensor([[-1.],
        [ 4.]])


## Tensorflow

In [29]:
# selesaikan persamaan berikut menggunakan tensorflow
# 4b + 2c = 4
# -5b + -3c = -7
A = tf.Variable([[4, 2], [-5, -3]], dtype=tf.float64)
B = tf.Variable([[4], [-7]], dtype=tf.float64)
C = tf.linalg.solve(A, B)
print(C)

tf.Tensor(
[[-1.]
 [ 4.]], shape=(2, 1), dtype=float64)
