In [1]:
import numpy as np
import torch as pt
import tensorflow as tf

# No 1

In [3]:
# buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy

A = np.array([[14, 62, 93], [42, 53, 60]])
b = np.array([[57], [58], [95]])
print(A)
print(b)

[[14 62 93]
 [42 53 60]]
[[57]
 [58]
 [95]]


In [4]:
# buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch

A_pt = pt.tensor([[33, 32, 95], [22, 63, 81]])
b_pt = pt.tensor([[67], [88], [95]])
print(A_pt)
print(b_pt)

tensor([[33, 32, 95],
        [22, 63, 81]])
tensor([[67],
        [88],
        [95]])


In [7]:
# buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
A_tf = tf.Variable([[83, 52, 45], [22, 66, 71]])
b_tf = tf.Variable([[70], [83], [90]])
print(A_tf)
print(b_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[83, 52, 45],
       [22, 66, 71]])>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[70],
       [83],
       [90]])>


# No 2

In [13]:
# tampilkan ukuran matrix A dan vector b
print("Ukuran matrix A:", A.shape)
print("Ukuran vector b:", b.shape)

Ukuran matrix A: (2, 3)
Ukuran vector b: (3, 1)


# No 3

In [19]:
# kalikan matrix A dengan vector b
np.dot(A, b)
print("Hasil perkalian matrix A dan vector b : \n", np.dot(A, b))

Hasil perkalian matrix A dan vector b : 
 [[13229]
 [11168]]


In [20]:
# kalikan matrix A_pt dengan vector b_pt
pt.matmul(A_pt, b_pt)
print("Hasil perkalian matrix A_pt dan vector b_pt : \n", pt.matmul(A_pt, b_pt))

Hasil perkalian matrix A_pt dan vector b_pt : 
 tensor([[14052],
        [14713]])


In [27]:
# kalikan matrix A_tf dengan vector b_tf
tf.linalg.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14176],
       [13408]])>

# No 4

In [ ]:
# buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[14, 62, 93], [42, 53, 60], [71, 82, 93]])
print(B)

[[14 62 93]
 [42 53 60]
 [71 82 93]]


In [29]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = pt.tensor([[34, 52, 73], [22, 55, 67], [31, 82, 13]])
print(B_pt)

tensor([[34, 52, 73],
        [22, 55, 67],
        [31, 82, 13]])


In [30]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[54, 92, 43], [26, 75, 97], [31, 80, 53]])
print(B_tf)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[54, 92, 43],
       [26, 75, 97],
       [31, 80, 53]])>


# No 5

In [ ]:
# kalikan matrix A dengan matrix B
np.dot(A, B)

array([[ 9403, 11780, 13671],
       [ 7074, 10333, 12666]])

In [32]:
# kalikan matrix A_pt dengan matrix B_pt
pt.matmul(A_pt, B_pt)

tensor([[ 4771, 11266,  5788],
        [ 4645, 11251,  6880]])

In [33]:
# kalikan matrix A_tf dengan matrix B_tf
tf.linalg.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7229, 15136, 10998],
       [ 5105, 12654, 11111]])>

# No 6

In [45]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
# np.array_equal(np.dot(A, B), np.dot(B, A)) jika di run akan menghasilkan False karena AB tidak sama dengan BA
print("Perkalian matrix A dan B tidak bersifat komutatif karena AB tidak sama dengan BA")

Perkalian matrix A dan B tidak bersifat komutatif karena AB tidak sama dengan BA
