In [4]:
import numpy as np
import torch as pt

# No 1

In [9]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
X_sym = np.array([[23, 42, 73], [42, 55, 53], [73, 53, 96]])
print(X_sym)
X_sym.T
print(X_sym.T == X_sym)

[[23 42 73]
 [42 55 53]
 [73 53 96]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# No 2

In [18]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
I = pt.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
print(I)

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])


In [19]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = pt.tensor([[32], [62], [65], [98]])
print(b_pt)

tensor([[32],
        [62],
        [65],
        [98]])


In [22]:
# kalikan matrix I dengan vector b_pt
pt.matmul(I, b_pt)

tensor([[32],
        [62],
        [65],
        [98]])